/**
 * play-golf
 * play golf API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvitationStatus } from './invitationStatus';
import { Address } from './address';
import { VerificationToken } from './verificationToken';


export interface ContactDetails { 
    firstName?: string;
    lastName?: string;
    nickname?: string;
    /**
     * A valid email address.
     */
    email?: string;
    /**
     * A valid phone number.
     */
    phone?: string;
    id?: string;
    ownerId?: string;
    profileId?: string;
    address?: Address;
    status?: InvitationStatus;
    since?: string;
    token?: VerificationToken;
}
export namespace ContactDetails {
}


