/**
 * play-golf
 * play golf API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type InvitationStatus = 'New' | 'Pending' | 'Accepted' | 'Declined' | 'Expired';

export const InvitationStatus = {
    New: 'New' as InvitationStatus,
    Pending: 'Pending' as InvitationStatus,
    Accepted: 'Accepted' as InvitationStatus,
    Declined: 'Declined' as InvitationStatus,
    Expired: 'Expired' as InvitationStatus
};

