/**
 * play-golf
 * play golf API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RoleType = 'Player' | 'Facilitator' | 'Delegate' | 'Administrator' | 'Creator';

export const RoleType = {
    Player: 'Player' as RoleType,
    Facilitator: 'Facilitator' as RoleType,
    Delegate: 'Delegate' as RoleType,
    Administrator: 'Administrator' as RoleType,
    Creator: 'Creator' as RoleType
};

