/**
 * play-golf
 * play golf API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Social media links
 */
export interface SocialLinks { 
    /**
     * A valid social media handle.
     */
    facebookHandle?: string;
    /**
     * A valid social media handle.
     */
    instagramHandle?: string;
    /**
     * A valid social media handle.
     */
    twitterHandle?: string;
    website?: string;
}

