/**
 * play-golf
 * play golf API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';


export interface CourseSummary { 
    id?: string;
    name?: string;
    /**
     * Set to true for publicly visible courses
     */
    managed?: boolean;
    address?: Address;
    /**
     * A valid social media handle.
     */
    facebookHandle?: string;
    /**
     * A valid social media handle.
     */
    instagramHandle?: string;
    /**
     * A valid social media handle.
     */
    twitterHandle?: string;
    /**
     * A valid Universal Resource Locator.
     */
    website?: string;
    /**
     * A valid phone number.
     */
    phone?: string;
    /**
     * A valid email address.
     */
    email?: string;
}

