/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GolfParticipant } from './golfParticipant';
import { Location } from './location';


export interface GolfGroupDetails { 
    id?: string;
    name?: string;
    description?: string;
    invitation?: string;
    rules?: string;
    location?: Location;
    participants?: Array<GolfParticipant>;
    roles?: Set<GolfGroupDetails.RolesEnum>;
}
export namespace GolfGroupDetails {
    export type RolesEnum = 'Player' | 'Facilitator' | 'Delegate' | 'Administrator' | 'Creator';
    export const RolesEnum = {
        Player: 'Player' as RolesEnum,
        Facilitator: 'Facilitator' as RolesEnum,
        Delegate: 'Delegate' as RolesEnum,
        Administrator: 'Administrator' as RolesEnum,
        Creator: 'Creator' as RolesEnum
    };
}


