/**
 * play-golf
 * play golf API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Paging and sorting options used in queries
 */
export interface PageAndSortRequest { 
    /**
     * Page offset starting at 0
     */
    page?: number;
    /**
     * How many items to return in the result (items per page)
     */
    size?: number;
    /**
     * Sorting options, prefix the option with a minus sign \'-\' to reverse sort
     */
    sort?: Array<string>;
}

