/**
 * play-golf
 * play golf API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Gender } from './gender';


/**
 * Supports storing the ratings per tee station as per the USGA Course Ratings site
 */
export interface TeeStation { 
    id?: string;
    name?: string;
    /**
     * Color definition as per HTML
     */
    color?: string;
    gender?: Gender;
    /**
     * Number of holes, typically 9 or 18 but there may be some oddballs
     */
    numberOfHoles?: number;
    /**
     * Par for the number of holes on the course (typically 71 or 72)
     */
    par?: number;
    /**
     * Total yardage for all holes on this tee
     */
    yardage?: number;
    /**
     * See the USGA web site
     */
    courseRating?: number;
    /**
     * See the USGA web site
     */
    bogeyRating?: number;
    /**
     * See the USGA web site
     */
    slopeRating?: number;
}
export namespace TeeStation {
}


